services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin@mongodb:27017/db?authSource=admin"
    depends_on:
      - mongodb

  object_storage:
    image: minio/minio:latest
    container_name: object-storage
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: localadmin
      MINIO_ROOT_PASSWORD: localpassword
    volumes:
      - object_storage_data:/data

  meilisearch:
      image: getmeili/meilisearch:v1.7
      container_name: meilisearch
      restart: unless-stopped
      ports:
        - "7700:7700"
      environment:
        MEILI_MASTER_KEY: "masterKey"
        MEILI_NO_ANALYTICS: "true"
        MEILI_ENV: "development"

      volumes:
        - meilisearch_data:/meili_data

volumes:
  mongodb_data:
  object_storage_data:
  meilisearch_data: